import type {
  Artist,
  ConcertEvent,
  Promo,
  TicketCategory,
  User,
  Venue,
} from "@/lib/types";

export const seedArtists: Artist[] = [
  { id: "ar_soundwave", name: "Soundwave Collective", genre: "Festival", image: "/posters/soundwave.jpg", bio: "Kolaborasi 12 DJ dan produser terbaik Asia Tenggara dalam satu panggung spektakuler." },
  { id: "ar_java", name: "Java Beat Orchestra", genre: "Festival", image: "/posters/java-music.jpg", bio: "Perpaduan orkestra modern dan musik elektronik dengan sentuhan budaya Nusantara." },
  { id: "ar_rockets", name: "The Rockets", genre: "Rock", image: "/posters/rock-revolution.jpg", bio: "Band rock legendaris yang membakar panggung dengan riff gitar dan energi yang meledak-ledak." },
  { id: "ar_summer", name: "Summer Rays", genre: "EDM", image: "/posters/summer-beats.jpg", bio: "Duo DJ yang membawa sinar matahari ke panggung dengan house music tropis." },
  { id: "ar_indie", name: "Indie Bloom", genre: "Indie", image: "/posters/indie-night.jpg", bio: "Band indie pujaan anak muda dengan lirik puitis dan melodi yang menenangkan." },
  { id: "ar_neon", name: "Neon Pulse", genre: "EDM", image: "/posters/edm-universe.jpg", bio: "Produser electronic dengan visual futuristik dan bass yang menggetarkan." },
  { id: "ar_coldplay", name: "Coldplay", genre: "Pop Rock", image: "/posters/coldplay-live.jpg", bio: "Band rock alternatif asal London yang memukau dunia dengan konser spektakuler." },
  { id: "ar_tulus", name: "Tulus", genre: "Pop", image: "/posters/tulus-harmoni.jpg", bio: "Penyanyi dan penulis lagu dengan vokal khas dan lirik yang menyentuh hati." },
  { id: "ar_dewa", name: "Dewa 19", genre: "Rock", image: "/posters/dewa19.jpg", bio: "Legenda musik rock Indonesia dengan deretan hits yang tak lekang oleh waktu." },
  { id: "ar_niki", name: "NIKI", genre: "R&B", image: "/posters/niki-moonchild.jpg", bio: "Penyanyi R&B asal Jakarta yang bersinar di panggung internasional." },
  { id: "ar_star", name: "Star Kids", genre: "K-Pop", image: "/posters/star-kids.jpg", bio: "Grup idola K-Pop dengan koreografi memukau dan lagu yang addicting." },
  { id: "ar_melodi", name: "Melodi Cinta", genre: "Dangdut", image: "/posters/dangdut-melodi.jpg", bio: "Diva dangdut tanah air dengan goyangan khas dan lagu yang menghentak." },
  { id: "ar_jazz", name: "Jazz Fusion Quintet", genre: "Jazz", image: "/posters/jazz-city.jpg", bio: "Kuintet jazz yang memadukan improvisasi klasik dengan nuansa modern." },
  { id: "ar_hiphop", name: "MC Mastermind", genre: "Hip Hop", image: "/posters/hiphop-takeover.jpg", bio: "Rapper dengan lirik tajam dan flow yang memukau, siap mengguncang kota." },
];

export const seedVenues: Venue[] = [
  { id: "vn_gbk", name: "Gelora Bung Karno Main Stadium", city: "Jakarta", address: "Jl. Pintu Satu Senayan, Tanah Abang, Jakarta Pusat", capacity: 77800, description: "Stadion terbesar di Indonesia dengan panggung megah dan kapasitas luar biasa." },
  { id: "vn_istora", name: "Istora Senayan", city: "Jakarta", address: "Jl. Pintu Satu Senayan, Gelora, Tanah Abang, Jakarta Pusat", capacity: 15000, description: "Indoor stadium ikonik dengan akustik yang hangat dan intim." },
  { id: "vn_beachcity", name: "Beach City International Stadium", city: "Jakarta", address: "Ancol, Pademangan, Jakarta Utara", capacity: 30000, description: "Stadion pesisir dengan pemandangan laut dan fasilitas modern." },
  { id: "vn_bandung", name: "Gelora Bandung Lautan Api", city: "Bandung", address: "Jl. Taman Sari No.1, Kota Bandung", capacity: 38000, description: "Kandang Pangeran Biru yang penuh dengan atmosfer panas khas Bandung." },
  { id: "vn_bungtomo", name: "Gelora Bung Tomo", city: "Surabaya", address: "Jl. Ikan Tenggiri No.1, Perak, Surabaya", capacity: 50000, description: "Stadion kebanggaan warga Surabaya dengan tribun yang dekat dengan panggung." },
  { id: "vn_gwk", name: "Garuda Wisnu Kencana Cultural Park", city: "Bali", address: "Jl. Raya Uluwatu, Ungasan, Kuta Selatan", capacity: 20000, description: "Venue terbuka megah di bawah patung GWK dengan pemandangan Bukit Uluwatu." },
  { id: "vn_jec", name: "Jogja Expo Center", city: "Yogyakarta", address: "Jl. Raya Janti, Banguntapan, Bantul", capacity: 15000, description: "Gedung ekspo modern dengan lahan parkir luas di jantung Yogyakarta." },
  { id: "vn_ice", name: "Indonesia Convention Exhibition", city: "Tangerang", address: "Jl. BSD Grand Boulevard, Bumi Serpong Damai", capacity: 50000, description: "MICE venue terbesar di Indonesia dengan hall fleksibel untuk festival." },
  { id: "vn_medan", name: "Merdeka Square Open Stage", city: "Medan", address: "Jl. Merdeka, Medan Petisah", capacity: 25000, description: "Lapangan terbuka bersejarah yang ikonik di pusat kota Medan." },
];

const tc = (
  name: string,
  price: number,
  quantity: number,
  sold: number,
  benefits: string[],
  isSeated = false,
  sectionId?: string
): TicketCategory => ({
  id: `tc_${name.toLowerCase().replace(/[^a-z]/g, "")}_${price}`,
  name,
  price,
  quantity,
  sold,
  benefits,
  isSeated,
  sectionId,
});

const seatLayout = (prefix: string) => ({
  id: `seatmap_${prefix}`,
  sections: [
    { id: `sec_vip_${prefix}`, name: "VIP", color: "#a78bfa", rows: ["A", "B", "C", "D"], cols: 12 },
    { id: `sec_prem_${prefix}`, name: "PREMIUM", color: "#22d3ee", rows: ["E", "F", "G", "H", "I"], cols: 14 },
    { id: `sec_reg_${prefix}`, name: "REGULAR", color: "#fb923c", rows: ["J", "K", "L", "M", "N"], cols: 16 },
  ],
});

export const seedEvents: ConcertEvent[] = [
  {
    id: "ev_soundwave",
    slug: "soundwave-festival-2026",
    title: "Soundwave Festival 2026",
    artistId: "ar_soundwave",
    category: "Festival",
    description: "Festival musik terbesar tahun ini dengan 12 panggung dan 50+ penampil dunia.",
    longDescription:
      "Soundwave Festival 2026 kembali dengan konsep yang lebih besar dan lebih spektakuler. 12 panggung, 50+ penampil internasional dan lokal, zona kuliner premium, serta pengalaman visual yang belum pernah ada sebelumnya. Satu hari, satu kota, ribuan memori yang tak terlupakan.",
    poster: "/posters/soundwave.jpg",
    date: "2026-09-12",
    time: "16:00",
    venueId: "vn_gbk",
    status: "published",
    featured: true,
    badges: ["hot", "best_seller"],
    ticketCategories: [
      tc("VIP", 1500000, 500, 340, ["Exclusive entrance", "Merchandise bundle", "VIP area", "Meet & greet", "Unlimited water"], false),
      tc("Festival", 750000, 5000, 3900, ["Full access festival", "All stages", "Festival wristband", "Access to food bazaar"], false),
      tc("Regular", 450000, 8000, 6100, ["General admission", "All stages access"], false),
    ],
    hasSeatLayout: false,
    tags: ["festival", "jakarta", "international", "all-day"],
    views: 12400,
  },
  {
    id: "ev_javamusic",
    slug: "java-music-fest",
    title: "Java Music Fest",
    artistId: "ar_java",
    category: "Festival",
    description: "Perpaduan orkestra modern dan musik elektronik ala Nusantara.",
    longDescription:
      "Java Music Fest menghadirkan perpaduan unik antara orkestra modern, gamelan digital, dan DJ internasional. Sebuah perayaan budaya dan musik yang memikat, di tepi pantai Ancol.",
    poster: "/posters/java-music.jpg",
    date: "2026-08-30",
    time: "17:00",
    venueId: "vn_beachcity",
    status: "published",
    featured: true,
    badges: ["best_seller"],
    ticketCategories: [
      tc("VIP", 1200000, 400, 310, ["Exclusive entrance", "Merchandise bundle", "VIP area", "Meet & greet"], false),
      tc("Festival", 650000, 4500, 3700, ["Full access", "Festival wristband", "Sunset zone"], false),
      tc("Regular", 400000, 6000, 4300, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["festival", "jakarta", "culture", "beach"],
    views: 9300,
  },
  {
    id: "ev_rockrev",
    slug: "rock-revolution",
    title: "Rock Revolution",
    artistId: "ar_rockets",
    category: "Rock",
    description: "The Rockets tampil live membakar panggung GBK.",
    longDescription:
      "The Rockets bersiap mengguncang Gelora Bung Karno dengan setlist terbaik sepanjang karier mereka. Riff gitar membara, drum yang menghentak, dan malam penuh energi rock.",
    poster: "/posters/rock-revolution.jpg",
    date: "2026-07-25",
    time: "19:00",
    venueId: "vn_gbk",
    status: "published",
    featured: true,
    badges: ["hot"],
    ticketCategories: [
      tc("VIP", 2000000, 300, 215, ["Front row access", "Meet & greet", "Signed poster", "Lanyard VIP"], true, "sec_vip_ev_rockrev"),
      tc("Premium", 1100000, 700, 460, ["Premium seating", "Priority entrance", "Merchandise"], true, "sec_prem_ev_rockrev"),
      tc("Regular", 600000, 1500, 1090, ["General seating"], true, "sec_reg_ev_rockrev"),
    ],
    hasSeatLayout: true,
    seatMap: seatLayout("ev_rockrev"),
    tags: ["rock", "jakarta", "seated", "the-rockets"],
    views: 11200,
  },
  {
    id: "ev_summerbeats",
    slug: "summer-beats",
    title: "Summer Beats",
    artistId: "ar_summer",
    category: "EDM",
    description: "House music tropis di bawah langit Bali.",
    longDescription:
      "Summer Beats membawa energi liburan ke Bukit Uluwatu. DJ terbaik memutarkan set house tropis saat matahari terbenam, di bawah patung GWK yang megah.",
    poster: "/posters/summer-beats.jpg",
    date: "2026-07-11",
    time: "15:00",
    venueId: "vn_gwk",
    status: "published",
    featured: true,
    badges: ["limited"],
    ticketCategories: [
      tc("VIP", 1300000, 200, 195, ["Exclusive entrance", "VIP deck", "Free drinks", "After party access"], false),
      tc("Festival", 700000, 3000, 2800, ["Full access", "Beach zone", "Festival wristband"], false),
      tc("Regular", 450000, 4000, 3200, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["edm", "bali", "beach", "sunset"],
    views: 8700,
  },
  {
    id: "ev_indienight",
    slug: "indie-night",
    title: "Indie Night",
    artistId: "ar_indie",
    category: "Indie",
    description: "Malam indie yang intim bersama Indie Bloom di Jogja.",
    longDescription:
      "Jogja selalu menjadi rumah bagi musik indie. Malam ini, Indie Bloom dan 8 band indie lainnya tampil dalam suasana intim yang hangat penuh lirik puitis.",
    poster: "/posters/indie-night.jpg",
    date: "2026-10-03",
    time: "19:00",
    venueId: "vn_jec",
    status: "published",
    featured: false,
    badges: ["hot"],
    ticketCategories: [
      tc("VIP", 600000, 200, 140, ["Front area", "Meet the band", "Merchandise"], false),
      tc("Regular", 300000, 1500, 980, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["indie", "yogyakarta", "intimate"],
    views: 6100,
  },
  {
    id: "ev_edmuniverse",
    slug: "edm-universe",
    title: "EDM Universe",
    artistId: "ar_neon",
    category: "EDM",
    description: "Raksasa electronic dance music dengan visual futuristik.",
    longDescription:
      "EDM Universe adalah perayaan musik elektronik terbesar di Indonesia. Panggung 360 derajat, visual hologram, dan bass yang bisa dirasakan hingga ke tulang.",
    poster: "/posters/edm-universe.jpg",
    date: "2026-08-15",
    time: "18:00",
    venueId: "vn_ice",
    status: "published",
    featured: true,
    badges: ["hot", "best_seller"],
    ticketCategories: [
      tc("VIP", 1400000, 400, 350, ["VIP deck", "Free flow drinks", "Exclusive entrance", "Merchandise"], false),
      tc("Festival", 750000, 6000, 5200, ["Full access", "Main stage & second stage", "Wristband"], false),
      tc("Regular", 500000, 8000, 5600, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["edm", "tangerang", "electronic", "visual"],
    views: 14800,
  },
  {
    id: "ev_coldplay",
    slug: "coldplay-live-jakarta",
    title: "Coldplay Live Jakarta",
    artistId: "ar_coldplay",
    category: "Pop Rock",
    description: "Pengalaman konser spektakuler yang paling dinanti tahun ini.",
    longDescription:
      "Coldplay kembali ke Jakarta membawa tour paling spektakuler mereka. Light wristbands, visual megah, dan deretan lagu hits yang dinyanyikan puluhan ribu penggemar. Sayangnya tiket telah habis terjual.",
    poster: "/posters/coldplay-live.jpg",
    date: "2026-11-21",
    time: "19:00",
    venueId: "vn_gbk",
    status: "published",
    featured: true,
    badges: ["sold_out", "limited"],
    ticketCategories: [
      tc("VIP", 3500000, 500, 500, ["Front of stage", "Ultimate experience", "Xylobands", "Merchandise"], true, "sec_vip_ev_coldplay"),
      tc("Premium", 2200000, 1000, 1000, ["Premium seating", "Xylobands"], true, "sec_prem_ev_coldplay"),
      tc("Regular", 1200000, 3000, 3000, ["General seating"], true, "sec_reg_ev_coldplay"),
    ],
    hasSeatLayout: true,
    seatMap: seatLayout("ev_coldplay"),
    tags: ["coldplay", "jakarta", "international", "sold-out"],
    views: 32100,
  },
  {
    id: "ev_tulus",
    slug: "tulus-harmoni",
    title: "Tulus Harmoni",
    artistId: "ar_tulus",
    category: "Pop",
    description: "Malam penuh harmoni bersama Tulus di Istora.",
    longDescription:
      "Suara khas Tulus menghiasi Istora Senayan dalam format panggung yang intim. Simfoni orkestra mengiringi setiap lagu dalam konser yang menyentuh hati.",
    poster: "/posters/tulus-harmoni.jpg",
    date: "2026-09-05",
    time: "20:00",
    venueId: "vn_istora",
    status: "published",
    featured: true,
    badges: ["best_seller"],
    ticketCategories: [
      tc("VIP", 1800000, 300, 260, ["Front row", "Meet & greet", "Signed merchandise"], true, "sec_vip_ev_tulus"),
      tc("Premium", 1000000, 600, 480, ["Premium seating", "Priority entrance"], true, "sec_prem_ev_tulus"),
      tc("Regular", 550000, 1200, 890, ["General seating"], true, "sec_reg_ev_tulus"),
    ],
    hasSeatLayout: true,
    seatMap: seatLayout("ev_tulus"),
    tags: ["pop", "jakarta", "seated", "tulus"],
    views: 13500,
  },
  {
    id: "ev_dewa19",
    slug: "dewa19-30-years-rockestra",
    title: "Dewa 19 30 Years Rockestra",
    artistId: "ar_dewa",
    category: "Rock",
    description: "Tiga dekade Dewa 19 dirayakan dengan rockestra megah.",
    longDescription:
      "Perayaan tiga dekade Dewa 19 dengan 30 lagu pilihan yang diaransemen ulang bersama orkestra. Malam nostalgia untuk seluruh generasi penggemar musik Indonesia.",
    poster: "/posters/dewa19.jpg",
    date: "2026-12-05",
    time: "19:30",
    venueId: "vn_gbk",
    status: "published",
    featured: true,
    badges: ["hot"],
    ticketCategories: [
      tc("VIP", 2500000, 300, 180, ["Front row", "Meet & greet", "Commemorative merch"], false),
      tc("Festival", 900000, 4000, 2100, ["Full access", "Wristband"], false),
      tc("Regular", 550000, 6000, 3100, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["rock", "jakarta", "dewa19", "anniversary"],
    views: 10400,
  },
  {
    id: "ev_niki",
    slug: "niki-moonchild-tour",
    title: "NIKI: Moonchild Tour",
    artistId: "ar_niki",
    category: "R&B",
    description: "Malam R&B yang intim bersama NIKI.",
    longDescription:
      "Putri Jakarta yang menjadi bintang global kembali ke rumah. NIKI membawakan lagu-lagu dari seluruh diskografinya dengan balutan R&B yang halus dan penuh perasaan.",
    poster: "/posters/niki-moonchild.jpg",
    date: "2026-10-17",
    time: "20:00",
    venueId: "vn_istora",
    status: "published",
    featured: true,
    badges: ["hot"],
    ticketCategories: [
      tc("VIP", 2200000, 250, 190, ["Front row", "Soundcheck access", "Meet & greet"], true, "sec_vip_ev_niki"),
      tc("Premium", 1200000, 500, 380, ["Premium seating", "Priority entrance"], true, "sec_prem_ev_niki"),
      tc("Regular", 700000, 1000, 720, ["General seating"], true, "sec_reg_ev_niki"),
    ],
    hasSeatLayout: true,
    seatMap: seatLayout("ev_niki"),
    tags: ["rnb", "jakarta", "seated", "niki"],
    views: 11800,
  },
  {
    id: "ev_starkids",
    slug: "star-kids-world-tour",
    title: "Star Kids World Tour",
    artistId: "ar_star",
    category: "K-Pop",
    description: "Sensasi K-Pop Star Kids menyapa penggemar Indonesia.",
    longDescription:
      "Grup idola K-Pop Star Kids membawa world tour mereka ke Jakarta. Koreografi presisi, visual memukau, dan interaksi langsung dengan penggemar. Jumlah tiket sangat terbatas.",
    poster: "/posters/star-kids.jpg",
    date: "2027-01-16",
    time: "18:00",
    venueId: "vn_gbk",
    status: "published",
    featured: true,
    badges: ["limited"],
    ticketCategories: [
      tc("VIP", 3200000, 300, 295, ["Front of stage", "Hi-touch session", "Official merch"], false),
      tc("Festival", 1800000, 2000, 1900, ["Full access", "Fan chant kit"], false),
      tc("Regular", 1000000, 3000, 2400, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["kpop", "jakarta", "star-kids", "limited"],
    views: 21800,
  },
  {
    id: "ev_dangdut",
    slug: "konser-dangdut-melodi-cinta",
    title: "Konser Dangdut Melodi Cinta",
    artistId: "ar_melodi",
    category: "Dangdut",
    description: "Malam bergoyang bersama diva dangdut Melodi Cinta.",
    longDescription:
      "Melodi Cinta siap memanjakan penggemar dangdut di Medan dengan lagu-lagu hits dan goyangan khas yang membuat seluruh lapangan bergoyang.",
    poster: "/posters/dangdut-melodi.jpg",
    date: "2026-08-08",
    time: "20:00",
    venueId: "vn_medan",
    status: "published",
    featured: false,
    badges: [],
    ticketCategories: [
      tc("VIP", 500000, 300, 180, ["Front area", "Meet & greet"], false),
      tc("Festival", 250000, 3000, 1600, ["Full access"], false),
      tc("Regular", 150000, 5000, 2900, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["dangdut", "medan"],
    views: 4600,
  },
  {
    id: "ev_jazzcity",
    slug: "jazz-in-the-city",
    title: "Jazz in the City",
    artistId: "ar_jazz",
    category: "Jazz",
    description: "Elegansi musik jazz di kota pelajar.",
    longDescription:
      "Jazz in the City menghadirkan Jazz Fusion Quintet beserta musisi jazz lokal dalam suasana malam yang tenang dan elegan di Jogja Expo Center.",
    poster: "/posters/jazz-city.jpg",
    date: "2026-09-19",
    time: "19:00",
    venueId: "vn_jec",
    status: "published",
    featured: false,
    badges: [],
    ticketCategories: [
      tc("VIP", 700000, 200, 120, ["Front seating", "After show", "Merchandise"], true, "sec_vip_ev_jazz"),
      tc("Premium", 450000, 400, 260, ["Premium seating"], true, "sec_prem_ev_jazz"),
      tc("Regular", 250000, 800, 410, ["General seating"], true, "sec_reg_ev_jazz"),
    ],
    hasSeatLayout: true,
    seatMap: seatLayout("ev_jazz"),
    tags: ["jazz", "yogyakarta", "seated", "elegant"],
    views: 3900,
  },
  {
    id: "ev_hiphop",
    slug: "hip-hop-takeover",
    title: "Hip Hop Takeover",
    artistId: "ar_hiphop",
    category: "Hip Hop",
    description: "MC Mastermind membawa scene hip hop Surabaya meledak.",
    longDescription:
      "Hip Hop Takeover menyatukan rapper terbaik Indonesia dan MC Mastermind di atas satu panggung. Malam penuh baris lirik tajam dan beat yang menghentak di Gelora Bung Tomo.",
    poster: "/posters/hiphop-takeover.jpg",
    date: "2026-08-22",
    time: "19:00",
    venueId: "vn_bungtomo",
    status: "published",
    featured: false,
    badges: ["hot"],
    ticketCategories: [
      tc("VIP", 800000, 300, 210, ["Front area", "Cypher access", "Merchandise"], false),
      tc("Regular", 350000, 2500, 1900, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["hiphop", "surabaya", "rap"],
    views: 5800,
  },
  {
    id: "ev_neonodeon",
    slug: "neon-odeon-nights",
    title: "Neon Odeon Nights",
    artistId: "ar_neon",
    category: "EDM",
    description: "Malam neon yang memukau di Bandung Lautan Api.",
    longDescription:
      "Neon Odeon Nights mengubah Gelora Bandung Lautan Api menjadi lautan cahaya neon. DJ line-up terbaik memimpin perayaan musik elektronik di Kota Kembang.",
    poster: "/posters/neon-odeon.jpg",
    date: "2026-10-24",
    time: "18:00",
    venueId: "vn_bandung",
    status: "published",
    featured: false,
    badges: ["best_seller"],
    ticketCategories: [
      tc("VIP", 1100000, 300, 250, ["VIP deck", "Free flow drinks", "Exclusive entrance"], false),
      tc("Festival", 600000, 4000, 3600, ["Full access", "Wristband"], false),
      tc("Regular", 400000, 5500, 3900, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["edm", "bandung", "electronic"],
    views: 7200,
  },
  {
    id: "ev_rnb",
    slug: "rnb-romance-night",
    title: "R&B Romance Night",
    artistId: "ar_niki",
    category: "R&B",
    description: "Malam romantis penuh irama R&B di Surabaya.",
    longDescription:
      "R&B Romance Night menghadirkan pilihan musisi R&B terbaik Indonesia dalam suasana yang hangat dan romantis di Gelora Bung Tomo.",
    poster: "/posters/rnb-romance.jpg",
    date: "2026-11-14",
    time: "19:30",
    venueId: "vn_bungtomo",
    status: "published",
    featured: false,
    badges: [],
    ticketCategories: [
      tc("VIP", 900000, 250, 160, ["Front area", "Couple perks", "Merchandise"], false),
      tc("Regular", 400000, 2000, 1300, ["General admission"], false),
    ],
    hasSeatLayout: false,
    tags: ["rnb", "surabaya", "romantic"],
    views: 4700,
  },
];

export const seedPromos: Promo[] = [
  {
    id: "promo_concert2026",
    code: "CONCERT2026",
    discountPercent: 20,
    maxDiscount: 100000,
    minPurchase: 500000,
    expiresAt: "2026-12-31",
    usageLimit: 1000,
    usedCount: 320,
    active: true,
  },
  {
    id: "promo_welcome10",
    code: "WELCOME10",
    discountPercent: 10,
    maxDiscount: 50000,
    minPurchase: 300000,
    expiresAt: "2026-12-31",
    usageLimit: 500,
    usedCount: 210,
    active: true,
  },
  {
    id: "promo_earlybird",
    code: "EARLYBIRD",
    discountPercent: 15,
    maxDiscount: 75000,
    minPurchase: 400000,
    expiresAt: "2026-10-31",
    usageLimit: 300,
    usedCount: 300,
    active: true,
  },
  {
    id: "promo_vipuxe",
    code: "VIPLUXE",
    discountPercent: 25,
    maxDiscount: 250000,
    minPurchase: 1000000,
    expiresAt: "2026-08-31",
    usageLimit: 100,
    usedCount: 100,
    active: false,
  },
];

export const seedUsers: User[] = [
  {
    id: "usr_admin",
    name: "TIXCONCERT Admin",
    email: "admin@tixconcert.com",
    phone: "081234567890",
    passwordHash: "a49abcc614c76105430b6c963a25d03745e82fb537286bbffa4226e4e1c29b9f",
    role: "admin",
    isSuspended: false,
    createdAt: "2025-11-01",
  },
  {
    id: "usr_staff",
    name: "Event Staff",
    email: "staff@tixconcert.com",
    phone: "081298765432",
    passwordHash: "5609cad26844c0638c9692140de59e2f1a670ca1a5b1c7b255e2e101c3eff9a7",
    role: "staff",
    isSuspended: false,
    createdAt: "2025-11-02",
  },
  {
    id: "usr_demo",
    name: "Ahmad Pratama",
    email: "user@tixconcert.com",
    phone: "081355511122",
    passwordHash: "5ae4844a122d4c4a0adbb4d13d8cd39f481fbdd962b0b42ab7eb75f5450007d1",
    role: "user",
    isSuspended: false,
    createdAt: "2025-11-10",
  },
  {
    id: "usr_ria",
    name: "Ria Anggraini",
    email: "ria@gmail.com",
    phone: "081377788899",
    passwordHash: "5ae4844a122d4c4a0adbb4d13d8cd39f481fbdd962b0b42ab7eb75f5450007d1",
    role: "user",
    isSuspended: false,
    createdAt: "2025-12-05",
  },
  {
    id: "usr_bayu",
    name: "Bayu Saputra",
    email: "bayu@gmail.com",
    phone: "081322233344",
    passwordHash: "5ae4844a122d4c4a0adbb4d13d8cd39f481fbdd962b0b42ab7eb75f5450007d1",
    role: "user",
    isSuspended: false,
    createdAt: "2026-01-15",
  },
];
